[workspace]
members = [
    "libs/base",
    "libs/alloc_data",
    "libs/charts",
    # "client",
    # "memthol",
]
# default-members = [
#     "memthol"
# ]

exclude = [
    "client",
    "memthol",
]

[profile.release]
lto = true
opt-level = 3